name = "homershie-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build" 

# R2 配置
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "hodes-images"
preview_bucket_name = "hodes-images" 